### PR TITLE
add fromFd API

### PR DESCRIPTION
**Pull request by sullyj3**

### CODE REVIEW

**Comment by sullyj3** [comment]
@hargoniX before I clean this up, does this approach with the additional bool field seem ok to you?

**Comment by hargoniX** [comment]
Yes, seems sensible to ensure at least some safety properties.

**Comment by sullyj3** [comment]
Ok, I think this is ready to go.

**Review by hargoniX — COMMENTED** [review]
The code that you wrote looks fine to me, I just have one additional question: Should `close` respect `owned`?

**Comment by sullyj3** [comment]
Imo no. The point of the field is to prevent unexpected implicit cleanup. If the user decides they want the socket closed, we should trust they know what they're doing, and it should be closed. In situations where like me, the user wants to use a socket provided by the parent process, they most likely should leave any closing to that parent, but that might not always be the case.

**Comment by sullyj3** [comment]
thanks!

**Pull request merged**
