### PR TITLE
Get the underlying file descriptor

### PR DESCRIPTION
**Pull request by Yuras**
Hello. First of all, thank you for making this package!

I'm working on [http-client for lean4](https://github.com/Yuras/lean4-http-client), and I'm using your package for the socket API.
Right now I'm adding https support using openssl, and I need to pass socket to [SSL_set_fd](https://www.openssl.org/docs/man3.1/man3/SSL_set_fd.html). I didn't find a way to get access to the underlying FD, so I went ahead and added a function for that.

### CODE REVIEW

**Review by hargoniX — CHANGES_REQUESTED** [review]
I would prefer not to expose an API like this to the user due to the fact that you need to keep the socket alive for this to work out. It can be hard to tell when a ref count is going to be incremented or decremented without inspecting IR.

I see three alternatives here:
- We define this function to be `unsafe`
- We remove the auto closing
- Specifically for the OpenSSL fd wrapper you could define a structure that keeps a reference to a `Socket` object + increments its refcount. Once you free that object you could decrement the refcount to the `Socket` object and thus force the socket to remain alive.

**Comment by Yuras** [comment]
Thank you for a quick response!

> It can be hard to tell when a ref count is going to be incremented or decremented without inspecting IR

I believe it's enough to call `close` on the socket at the very end, which will prevent it from being deallocated earlier.

> We define this function to be unsafe

I'm new to lean, so I don't fully understand the implications. I tried to throw `unsafe` and see what will happen like this:

```diff
-def getFd (socket : @& Socket) : UInt32 := {
+unsafe def getFd (socket : @& Socket) : UInt32 := {
```

but compiler complains: `error: unexpected token 'unsafe'; expected 'def'`. Could you please help me to do it properly?

> Specifically for the OpenSSL fd wrapper you could define a structure that keeps a reference to a Socket object

Of course I have something like this on my side (though I'm just relying on `sock.close` to keep the socket alive, see https://github.com/Yuras/lean4-http-client/blob/2fc483cd0ace383945b6a4502f102a725deacadb/HttpClient/Basic.lean#L101).
Though I don't see how it can be done on `socket.lean` side, could you please elaborate?

**Comment by Yuras** [comment]
As a side note, the API is already unsafe, and I kinda thought it's by design. E.g. there is nothing preventing sending to or receiving from a closed socket. E.g. the following code

```lean
      sock.connect addr
      sock.close
      let _ ← sock.recv 1000
```

fails with `uncaught exception: invalid argument (error code: 9, bad file descriptor)`. (Relying on `EBADF` is not enough since file descriptors are reused, so if someone opens another connection between `close` and `recv`, then you'll try to read from a completely unrelated socket. It's disaster.)

**Comment by hargoniX** [comment]
The `unsafe` error is most likely happening because that isn't implemented in alloy yet, it would work if this was vanilla Lean code. If we want to go that way we'll probably have to open an issue/PR in alloy that implements `unsafe` functions and get that merged then do it here.

The approach I detailed for the OpenSSL fd is not something that you can implement easily in a generic fashion without writing some FFI C yourself I believe, sadly we lack the Rust lifetime capabilities here :(.

The descriptor reuse and such is a good point I didn't think of that when whipping up this naive API. Maybe we should track whether `close` has been called on the `Socket` object before and only call `close` if the flag has not yet been set + only let method calls pass when the socket has not been closed? That would address all scenarios I can currently think of, is there something I'm missing? Would you like to write a PR for that as well or should I do it?

**Comment by Yuras** [comment]
> If we want to go that way we'll probably have to open an issue/PR in alloy

I'm not familiar with alloy (I'm writing my FFI bindings manually). So I guess I'll stick to my fork for now in this case.

> The approach I detailed for the OpenSSL fd is not something that you can implement easily in a generic fashion without writing some FFI C yourself I believe

I understand how lean4 FFI works, I made bindings to openssl and getaddrinfo(3) already for my http-client. And I have general idea how it could be done on my side, i.e. in http-client code. (Though I don't still see why it's necessary, since the existing approach works well)
The problem is that I don't understand what changes I have to make to this PR. I mean, I'll have to get the raw FD at some point, one way or another, so there is no way around a unsafe `getFd` or something similar.

> That would address all scenarios I can currently think of

I think so. Though I'm not an expert in networking, so don't quote me. I know about the issue only because I spent many hours debugging it at some point of my career.

> Would you like to write a PR for that as well or should I do it?

I already accounted for this in my code, so it's up to you. Depending on your design goals, you might decide to keep the API close to C, keeping it unsafe but flexible, or provide something higher level, which is safe but restrictive.

**Comment by hargoniX** [comment]
I addressed the closing issue in #8. I'll get `unsafe` support in alloy ASAP.

**Comment by hargoniX** [comment]
Closing in favor of #9

**Pull request closed without merging**
